language: node_js
compiler: gcc
env:
  global:
    - NODE_GLES_SKIP_BINARY_DOWNLOAD_FOR_CI=true
jobs:
  include:
    - stage: build
      node_js: "10"
      os: linux
    - stage: build
      node_js: "11"
      os: linux
    - stage: build
      node_js: "12"
      os: linux
    - stage: build
      node_js: "13"
      os: linux
    - stage: build
      node_js: "14"
      os: linux
    - stage: build
      node_js: "10"
      os: osx
    - stage: build
      node_js: "11"
      os: osx
    - stage: build
      node_js: "12"
      os: osx
    - stage: build
      node_js: "13"
      os: osx
    - stage: build
      node_js: "14"
      os: osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - make
      - git
before_install:
  - npm install -g yarn
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CC="gcc-7";
    export CXX="g++-7";
    export LINK="gcc-7";
    export LINKXX="g++-7";
    fi
  - node --version
  - yarn --version
script:
  - yarn build
after_script:
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
cache: yarn
deploy:
  provider: releases
  api_key:
    secure: P5VTXq1HtSp6cF2rv5kgdob/bH99Qj1USSfX419/tpIGRkB++WFQNOKiYdoeYPplKBUMqrZvy7nB9Qc/qyeyEd0I3ejUq0U8Lz6oj2AzDRuhyvoFH/xZTtu5RN6UEtV0us72TAGhEItyU+LZ+icxPFkKm/LIUtBul8N50Mx6vGRp/W+yIANdv1wGw5ntwvhIqCFgzj+SM8Knvp/ynSWfFZdYN5hENGY74bE9MrvOjq+KRDgK99YUkJh82MSFkh329qOCe27ItHPfQsCWVS9TQlEbKGvnq7oOqt5Bt3n85yuTMLLb91yAVgEr7ZWTkIEGvCG3qrztbnrCPkAikWS0ULxYvJ1N1xpl6acFj/pOjZn7gqyyZW9dawOxgRHNOJjs9V4khRijv5cCAgpHbcQML9+lLG0U11IJl66JD2D2gzy68l9rL4E3GT4rKhnyozDyVpmmDH6PGr6VGHUOkK/BcIKL02Dysy80/IidDmrMv6NlHulL/ixRnkb7G8np/Mw5SYVT4racRe9NGfXqtKQ6LzAi1QzXIVrT9+BD0WWHyrFkguCII5e5g30EbDKIvL/7KTYm8mz+95rm7OHuCpX62mPw3H5tz6hej3OokEJZ3lMm11yaUa3p2WtzSH6E9hkttgkbupTGhGpGRHdKswc8OAd/XUol6IN15ez32bY8BFY=
  file_glob: true
  file: "node-gles-*-*-*.node"
  skip_cleanup: true
  on:
    tags: true
